### ISSUE TITLE
Fuse related problem??

### ISSUE THREAD

**Issue by c8c-erzatz-info** [bentglasstube/secretfs#1]
Hi.

I think there is a problem related to fuse.

git clone https://github.com/bentglasstube/secretfs.git
cd secretfs
mkdir mountt
secretfs example-root mountt/
la mountt
# total 12K
# drwxr-xr-x 2 c8c users 4.0K Jan 22 17:07 ./
# drwxr-xr-x 6 c8c users 4.0K Jan 22 17:08 ../
# -r-------- 1 c8c users  120 Jan 22 17:07 test.txt

cat mountt/test.txt
# cat: mountt/test.txt: Software caused connection abort

I think it's related to fuse. But not sure. Have you used secretfs recently?

Regards

**Comment by bentglasstube** [comment]
My apologies, but I did not write secretfs so I don't really know much
about its inner workings.  I created this repo just to package it up for
AUR.

The steps you gave above are working for me on Ubuntu 14.04.3 LTS

On Fri, Jan 22, 2016 at 2:12 PM, c8c-erzatz-info notifications@github.com
wrote:

> Hi
> 
> I think there is a problem related to fuse
> 
> git clone https://githubcom/bentglasstube/secretfsgit
> cd secretfs
> mkdir mountt
> secretfs example-root mountt/
> la mountt
> total 12K drwxr-xr-x 2 c8c users 40K Jan 22 17:07 / drwxr-xr-x 6 c8c
> users 40K Jan 22 17:08 / -r-------- 1 c8c users 120 Jan 22 17:07 testtxt
> 
> cat mountt/testtxt
> cat: mountt/testtxt: Software caused connection abort
> 
> I think it's related to fuse But not sure Have you used secretfs recently?
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bentglasstube/secretfs/issues/1.

## 

Alan Berndt

**Comment by c8c-erzatz-info** [comment]
Where have you found the package then? Have you compiled it yourself?

**Comment by bentglasstube** [comment]
I compiled secretfs from the source in this package.

On Sun, Jan 24, 2016 at 06:46:04PM -0800, c8c-erzatz-info wrote:

> Where have you found the package then? Have you compiled it yourself? 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bentglasstube/secretfs/issues/1#issuecomment-174379110

## 

Alan Berndt

  Whether you think you can or you think you can't, you're right.
    - Henry Ford

**Comment by bentglasstube** [comment]
I just tried the steps you listed on my Arch Linux installation and it is giving me the same error as you had above.  As I said earlier, I don't know anything about how this software works, though.  Here is the original author's page:  http://www.digital-scurf.org/software/secretfs
